### ISSUE TITLE
license

### ISSUE THREAD

**Issue by serialhex** [xorgy/coffeescript-nano#2]
Hey, I just had an individual who was worried about some licensing stuff of the nano-highlight files, and I was wondering if you would mind - since I got the file from here anyway - if I included the coffeescript.nanorc file in the unlicence that I've put the rest of the repo under.  Linkage: http://unlicense.org/

Oh, and thanks for pointing people to my repo, it's kind of weird that I have so many people liking it, and all I really wanted was to share all the nano-highlighting-goodness that I've gathered...

**Comment by xorgy** [comment]
@serialhex Sure, I can drop it in the repository.

**Comment by xorgy** [comment]
Resolved with #3.

Enjoy, and good luck getting all the nano highlight files under a decent license so that they can finally be put into GNU Nano distributions. :- )

Side note: I figure it would be good enough (or maybe better) to give them the same license as GNU Nano itself.
